name: Upload Hoplite Python Package to PyPI when a release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish Hoplite release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/perch-hoplite
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsndfile1 ffmpeg
          pip install build
      - name: Build package
        run: |
          python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
